name: CI Build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - uses: swift-actions/setup-swift@v1.25.0
      - uses: lukka/get-cmake@latest
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-latest
      
      - name: Build & Run (Posix)
        if: (startsWith(matrix.runs-on, 'ubuntu')) || (startsWith(matrix.runs-on, 'macos'))
        run: sh run.sh

      - name: Build & Run (Windows)
        if: startsWith(matrix.runs-on, 'windows')
        run: ./run.ps1